/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RefereesRouteImport } from './routes/referees'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FederationRouteImport } from './routes/federation'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CourtsRouteImport } from './routes/courts'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as FederationIndexRouteImport } from './routes/federation.index'
import { Route as NewsNewsIdRouteImport } from './routes/news.$newsId'
import { Route as FederationEventsRouteImport } from './routes/federation.events'
import { Route as FederationDocumentsRouteImport } from './routes/federation.documents'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAuthedRouteRouteImport } from './routes/admin/_authed/route'
import { Route as AdminAuthedIndexRouteImport } from './routes/admin/_authed/index'
import { Route as ApiAdminUploadRouteImport } from './routes/api/admin/upload'
import { Route as AdminAuthedNewsIndexRouteImport } from './routes/admin/_authed/news.index'
import { Route as AdminAuthedDocumentsIndexRouteImport } from './routes/admin/_authed/documents.index'
import { Route as AdminAuthedNewsNewRouteImport } from './routes/admin/_authed/news.new'
import { Route as AdminAuthedNewsIdRouteImport } from './routes/admin/_authed/news.$id'
import { Route as AdminAuthedDocumentsNewRouteImport } from './routes/admin/_authed/documents.new'
import { Route as AdminAuthedDocumentsIdRouteImport } from './routes/admin/_authed/documents.$id'

const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RefereesRoute = RefereesRouteImport.update({
  id: '/referees',
  path: '/referees',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FederationRoute = FederationRouteImport.update({
  id: '/federation',
  path: '/federation',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CourtsRoute = CourtsRouteImport.update({
  id: '/courts',
  path: '/courts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const FederationIndexRoute = FederationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FederationRoute,
} as any)
const NewsNewsIdRoute = NewsNewsIdRouteImport.update({
  id: '/news/$newsId',
  path: '/news/$newsId',
  getParentRoute: () => rootRouteImport,
} as any)
const FederationEventsRoute = FederationEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => FederationRoute,
} as any)
const FederationDocumentsRoute = FederationDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => FederationRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuthedRouteRoute = AdminAuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuthedIndexRoute = AdminAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthedRouteRoute,
} as any)
const ApiAdminUploadRoute = ApiAdminUploadRouteImport.update({
  id: '/api/admin/upload',
  path: '/api/admin/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedNewsIndexRoute = AdminAuthedNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AdminAuthedRouteRoute,
} as any)
const AdminAuthedDocumentsIndexRoute =
  AdminAuthedDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AdminAuthedRouteRoute,
  } as any)
const AdminAuthedNewsNewRoute = AdminAuthedNewsNewRouteImport.update({
  id: '/news/new',
  path: '/news/new',
  getParentRoute: () => AdminAuthedRouteRoute,
} as any)
const AdminAuthedNewsIdRoute = AdminAuthedNewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => AdminAuthedRouteRoute,
} as any)
const AdminAuthedDocumentsNewRoute = AdminAuthedDocumentsNewRouteImport.update({
  id: '/documents/new',
  path: '/documents/new',
  getParentRoute: () => AdminAuthedRouteRoute,
} as any)
const AdminAuthedDocumentsIdRoute = AdminAuthedDocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => AdminAuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/courts': typeof CourtsRoute
  '/documents': typeof DocumentsRoute
  '/federation': typeof FederationRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/referees': typeof RefereesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teams': typeof TeamsRoute
  '/terms': typeof TermsRoute
  '/tournaments': typeof TournamentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/federation/documents': typeof FederationDocumentsRoute
  '/federation/events': typeof FederationEventsRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/federation/': typeof FederationIndexRoute
  '/news/': typeof NewsIndexRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/admin/': typeof AdminAuthedIndexRoute
  '/admin/documents/$id': typeof AdminAuthedDocumentsIdRoute
  '/admin/documents/new': typeof AdminAuthedDocumentsNewRoute
  '/admin/news/$id': typeof AdminAuthedNewsIdRoute
  '/admin/news/new': typeof AdminAuthedNewsNewRoute
  '/admin/documents/': typeof AdminAuthedDocumentsIndexRoute
  '/admin/news/': typeof AdminAuthedNewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminAuthedIndexRoute
  '/contacts': typeof ContactsRoute
  '/courts': typeof CourtsRoute
  '/documents': typeof DocumentsRoute
  '/privacy': typeof PrivacyRoute
  '/referees': typeof RefereesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teams': typeof TeamsRoute
  '/terms': typeof TermsRoute
  '/tournaments': typeof TournamentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/federation/documents': typeof FederationDocumentsRoute
  '/federation/events': typeof FederationEventsRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/federation': typeof FederationIndexRoute
  '/news': typeof NewsIndexRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/admin/documents/$id': typeof AdminAuthedDocumentsIdRoute
  '/admin/documents/new': typeof AdminAuthedDocumentsNewRoute
  '/admin/news/$id': typeof AdminAuthedNewsIdRoute
  '/admin/news/new': typeof AdminAuthedNewsNewRoute
  '/admin/documents': typeof AdminAuthedDocumentsIndexRoute
  '/admin/news': typeof AdminAuthedNewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/courts': typeof CourtsRoute
  '/documents': typeof DocumentsRoute
  '/federation': typeof FederationRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/referees': typeof RefereesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teams': typeof TeamsRoute
  '/terms': typeof TermsRoute
  '/tournaments': typeof TournamentsRoute
  '/admin/_authed': typeof AdminAuthedRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/federation/documents': typeof FederationDocumentsRoute
  '/federation/events': typeof FederationEventsRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/federation/': typeof FederationIndexRoute
  '/news/': typeof NewsIndexRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/admin/_authed/': typeof AdminAuthedIndexRoute
  '/admin/_authed/documents/$id': typeof AdminAuthedDocumentsIdRoute
  '/admin/_authed/documents/new': typeof AdminAuthedDocumentsNewRoute
  '/admin/_authed/news/$id': typeof AdminAuthedNewsIdRoute
  '/admin/_authed/news/new': typeof AdminAuthedNewsNewRoute
  '/admin/_authed/documents/': typeof AdminAuthedDocumentsIndexRoute
  '/admin/_authed/news/': typeof AdminAuthedNewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contacts'
    | '/courts'
    | '/documents'
    | '/federation'
    | '/privacy'
    | '/referees'
    | '/sitemap.xml'
    | '/teams'
    | '/terms'
    | '/tournaments'
    | '/admin/login'
    | '/federation/documents'
    | '/federation/events'
    | '/news/$newsId'
    | '/federation/'
    | '/news/'
    | '/api/admin/upload'
    | '/admin/'
    | '/admin/documents/$id'
    | '/admin/documents/new'
    | '/admin/news/$id'
    | '/admin/news/new'
    | '/admin/documents/'
    | '/admin/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contacts'
    | '/courts'
    | '/documents'
    | '/privacy'
    | '/referees'
    | '/sitemap.xml'
    | '/teams'
    | '/terms'
    | '/tournaments'
    | '/admin/login'
    | '/federation/documents'
    | '/federation/events'
    | '/news/$newsId'
    | '/federation'
    | '/news'
    | '/api/admin/upload'
    | '/admin/documents/$id'
    | '/admin/documents/new'
    | '/admin/news/$id'
    | '/admin/news/new'
    | '/admin/documents'
    | '/admin/news'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contacts'
    | '/courts'
    | '/documents'
    | '/federation'
    | '/privacy'
    | '/referees'
    | '/sitemap.xml'
    | '/teams'
    | '/terms'
    | '/tournaments'
    | '/admin/_authed'
    | '/admin/login'
    | '/federation/documents'
    | '/federation/events'
    | '/news/$newsId'
    | '/federation/'
    | '/news/'
    | '/api/admin/upload'
    | '/admin/_authed/'
    | '/admin/_authed/documents/$id'
    | '/admin/_authed/documents/new'
    | '/admin/_authed/news/$id'
    | '/admin/_authed/news/new'
    | '/admin/_authed/documents/'
    | '/admin/_authed/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ContactsRoute: typeof ContactsRoute
  CourtsRoute: typeof CourtsRoute
  DocumentsRoute: typeof DocumentsRoute
  FederationRoute: typeof FederationRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RefereesRoute: typeof RefereesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamsRoute: typeof TeamsRoute
  TermsRoute: typeof TermsRoute
  TournamentsRoute: typeof TournamentsRoute
  NewsNewsIdRoute: typeof NewsNewsIdRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ApiAdminUploadRoute: typeof ApiAdminUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referees': {
      id: '/referees'
      path: '/referees'
      fullPath: '/referees'
      preLoaderRoute: typeof RefereesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/federation': {
      id: '/federation'
      path: '/federation'
      fullPath: '/federation'
      preLoaderRoute: typeof FederationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courts': {
      id: '/courts'
      path: '/courts'
      fullPath: '/courts'
      preLoaderRoute: typeof CourtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/federation/': {
      id: '/federation/'
      path: '/'
      fullPath: '/federation/'
      preLoaderRoute: typeof FederationIndexRouteImport
      parentRoute: typeof FederationRoute
    }
    '/news/$newsId': {
      id: '/news/$newsId'
      path: '/news/$newsId'
      fullPath: '/news/$newsId'
      preLoaderRoute: typeof NewsNewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/federation/events': {
      id: '/federation/events'
      path: '/events'
      fullPath: '/federation/events'
      preLoaderRoute: typeof FederationEventsRouteImport
      parentRoute: typeof FederationRoute
    }
    '/federation/documents': {
      id: '/federation/documents'
      path: '/documents'
      fullPath: '/federation/documents'
      preLoaderRoute: typeof FederationDocumentsRouteImport
      parentRoute: typeof FederationRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/_authed': {
      id: '/admin/_authed'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthedRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/_authed/': {
      id: '/admin/_authed/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthedIndexRouteImport
      parentRoute: typeof AdminAuthedRouteRoute
    }
    '/api/admin/upload': {
      id: '/api/admin/upload'
      path: '/api/admin/upload'
      fullPath: '/api/admin/upload'
      preLoaderRoute: typeof ApiAdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed/news/': {
      id: '/admin/_authed/news/'
      path: '/news'
      fullPath: '/admin/news/'
      preLoaderRoute: typeof AdminAuthedNewsIndexRouteImport
      parentRoute: typeof AdminAuthedRouteRoute
    }
    '/admin/_authed/documents/': {
      id: '/admin/_authed/documents/'
      path: '/documents'
      fullPath: '/admin/documents/'
      preLoaderRoute: typeof AdminAuthedDocumentsIndexRouteImport
      parentRoute: typeof AdminAuthedRouteRoute
    }
    '/admin/_authed/news/new': {
      id: '/admin/_authed/news/new'
      path: '/news/new'
      fullPath: '/admin/news/new'
      preLoaderRoute: typeof AdminAuthedNewsNewRouteImport
      parentRoute: typeof AdminAuthedRouteRoute
    }
    '/admin/_authed/news/$id': {
      id: '/admin/_authed/news/$id'
      path: '/news/$id'
      fullPath: '/admin/news/$id'
      preLoaderRoute: typeof AdminAuthedNewsIdRouteImport
      parentRoute: typeof AdminAuthedRouteRoute
    }
    '/admin/_authed/documents/new': {
      id: '/admin/_authed/documents/new'
      path: '/documents/new'
      fullPath: '/admin/documents/new'
      preLoaderRoute: typeof AdminAuthedDocumentsNewRouteImport
      parentRoute: typeof AdminAuthedRouteRoute
    }
    '/admin/_authed/documents/$id': {
      id: '/admin/_authed/documents/$id'
      path: '/documents/$id'
      fullPath: '/admin/documents/$id'
      preLoaderRoute: typeof AdminAuthedDocumentsIdRouteImport
      parentRoute: typeof AdminAuthedRouteRoute
    }
  }
}

interface AdminAuthedRouteRouteChildren {
  AdminAuthedIndexRoute: typeof AdminAuthedIndexRoute
  AdminAuthedDocumentsIdRoute: typeof AdminAuthedDocumentsIdRoute
  AdminAuthedDocumentsNewRoute: typeof AdminAuthedDocumentsNewRoute
  AdminAuthedNewsIdRoute: typeof AdminAuthedNewsIdRoute
  AdminAuthedNewsNewRoute: typeof AdminAuthedNewsNewRoute
  AdminAuthedDocumentsIndexRoute: typeof AdminAuthedDocumentsIndexRoute
  AdminAuthedNewsIndexRoute: typeof AdminAuthedNewsIndexRoute
}

const AdminAuthedRouteRouteChildren: AdminAuthedRouteRouteChildren = {
  AdminAuthedIndexRoute: AdminAuthedIndexRoute,
  AdminAuthedDocumentsIdRoute: AdminAuthedDocumentsIdRoute,
  AdminAuthedDocumentsNewRoute: AdminAuthedDocumentsNewRoute,
  AdminAuthedNewsIdRoute: AdminAuthedNewsIdRoute,
  AdminAuthedNewsNewRoute: AdminAuthedNewsNewRoute,
  AdminAuthedDocumentsIndexRoute: AdminAuthedDocumentsIndexRoute,
  AdminAuthedNewsIndexRoute: AdminAuthedNewsIndexRoute,
}

const AdminAuthedRouteRouteWithChildren =
  AdminAuthedRouteRoute._addFileChildren(AdminAuthedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminAuthedRouteRoute: typeof AdminAuthedRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuthedRouteRoute: AdminAuthedRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface FederationRouteChildren {
  FederationDocumentsRoute: typeof FederationDocumentsRoute
  FederationEventsRoute: typeof FederationEventsRoute
  FederationIndexRoute: typeof FederationIndexRoute
}

const FederationRouteChildren: FederationRouteChildren = {
  FederationDocumentsRoute: FederationDocumentsRoute,
  FederationEventsRoute: FederationEventsRoute,
  FederationIndexRoute: FederationIndexRoute,
}

const FederationRouteWithChildren = FederationRoute._addFileChildren(
  FederationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ContactsRoute: ContactsRoute,
  CourtsRoute: CourtsRoute,
  DocumentsRoute: DocumentsRoute,
  FederationRoute: FederationRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RefereesRoute: RefereesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamsRoute: TeamsRoute,
  TermsRoute: TermsRoute,
  TournamentsRoute: TournamentsRoute,
  NewsNewsIdRoute: NewsNewsIdRoute,
  NewsIndexRoute: NewsIndexRoute,
  ApiAdminUploadRoute: ApiAdminUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
